### PR TITLE
Null is now treated the same way as undefined during the case-class serialization

### PR DESCRIPTION
**Pull request by OlegIlyenko**
@agourlay @yanns can you please review?

### CODE REVIEW

**Comment by yanns** [comment]
LGTM

I hope we will not have any side effect with that.
Have you checked our application with that change?

**Comment by OlegIlyenko** [comment]
not yet, but I will definitely do it before the merge of this PR

**Comment by yanns** [comment]
OK
:+1:

**Comment by OlegIlyenko** [comment]
@yanns I tested it with out application and it works fine. i don't see any side-effects.

@agourlay @gogregor I would appreciate if you could also quickly review this PR and give your opinion on this change.

**Comment by agourlay** [comment]
LGTM

**Comment by gogregor** [comment]
:+1:

**Comment by OlegIlyenko** [comment]
thanks!

**Pull request merged**
